### ISSUE TITLE
Use shared version of FreSwift

### ISSUE THREAD

**Issue by hferreira** [tuarua/DesktopToastANE#17]
I was checking the change log and I see that I need now 2 ANE's instead of one.
So , you was using your own SWIFT-OSX ANE embeded this one and now you split in two (a shared one), reducing th size on the ANE and preventing potencial conflit between several ANE's.
It's that the reason ?

**Comment by tuarua** [comment]
The second ANE contains the Swift core libraries.Before each ANE contained copies of these and it was wasteful if using multiple of my ANEs.I also had to tweak to resolve potential conflicts between the FREContext of each (mostly affected events).
This CommonDependencies.ane is applicable to OSX only. It can be included safely in Windows projects but contains no functionality.I need to still update WebViewANE with the shared library.
On Tuesday, July 11, 2017, 12:37:59 PM GMT+1, hferreira <notifications@github.com> wrote:


I was checking the change log and I see that I need now 2 ANE's instead of one.
So , you was using your own SWIFT-OSX ANE embeded this one and now you split in two (a shared one), reducing th size on the ANE and preventing potencial conflit between several ANE's.
It's that the reason ?

**Comment by hferreira** [comment]
As I thought.
The name makes pretty sense for me.
Besides, it's target right now only for macOS and SWIFT but you may use for other common features.
For example for FreSharp.
